# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_keys_api import ApiKeysApi


class TestApiKeysApi(unittest.TestCase):
    """ApiKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeysApi()

    def tearDown(self) -> None:
        pass

    def test_api_keys_controller_create(self) -> None:
        """Test case for api_keys_controller_create

        Create new API key
        """
        pass

    def test_api_keys_controller_find_my(self) -> None:
        """Test case for api_keys_controller_find_my

        Get your API keys
        """
        pass

    def test_api_keys_controller_remove(self) -> None:
        """Test case for api_keys_controller_remove

        Delete API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
