# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.membership_subscriptions_api import MembershipSubscriptionsApi


class TestMembershipSubscriptionsApi(unittest.TestCase):
    """MembershipSubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembershipSubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_membership_subscriptions_controller_find_all_by_member_id(self) -> None:
        """Test case for membership_subscriptions_controller_find_all_by_member_id

        Get all membership subscriptions for member
        """
        pass

    def test_membership_subscriptions_controller_find_all_by_membership_id(self) -> None:
        """Test case for membership_subscriptions_controller_find_all_by_membership_id

        Get all membership subscriptions for membership
        """
        pass

    def test_membership_subscriptions_controller_stats(self) -> None:
        """Test case for membership_subscriptions_controller_stats

        Get all membership subscriptions statistics
        """
        pass

    def test_membership_subscriptions_controller_subscribe(self) -> None:
        """Test case for membership_subscriptions_controller_subscribe

        Subscribe member to membership
        """
        pass

    def test_membership_subscriptions_controller_unsubscribe(self) -> None:
        """Test case for membership_subscriptions_controller_unsubscribe

        Unsubscribe member from membership
        """
        pass


if __name__ == '__main__':
    unittest.main()
