# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.memberships_api import MembershipsApi


class TestMembershipsApi(unittest.TestCase):
    """MembershipsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembershipsApi()

    def tearDown(self) -> None:
        pass

    def test_memberships_controller_create(self) -> None:
        """Test case for memberships_controller_create

        Create new membership
        """
        pass

    def test_memberships_controller_find_all(self) -> None:
        """Test case for memberships_controller_find_all

        Get all memberships
        """
        pass

    def test_memberships_controller_update_membership(self) -> None:
        """Test case for memberships_controller_update_membership

        Update membership
        """
        pass


if __name__ == '__main__':
    unittest.main()
