# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.macs_api import MacsApi


class TestMacsApi(unittest.TestCase):
    """MacsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MacsApi()

    def tearDown(self) -> None:
        pass

    def test_m_acs_controller_create(self) -> None:
        """Test case for m_acs_controller_create

        Create new MAC
        """
        pass

    def test_m_acs_controller_find_by_member_id(self) -> None:
        """Test case for m_acs_controller_find_by_member_id

        Get MACs for specific member
        """
        pass

    def test_m_acs_controller_remove(self) -> None:
        """Test case for m_acs_controller_remove

        Delete MAC
        """
        pass


if __name__ == '__main__':
    unittest.main()
