# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.membership_subscription_dto import MembershipSubscriptionDTO

class TestMembershipSubscriptionDTO(unittest.TestCase):
    """MembershipSubscriptionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MembershipSubscriptionDTO:
        """Test MembershipSubscriptionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MembershipSubscriptionDTO`
        """
        model = MembershipSubscriptionDTO()
        if include_optional:
            return MembershipSubscriptionDTO(
                id = '',
                member_id = '',
                membership_id = '',
                subscribed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                declined_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MembershipSubscriptionDTO(
                id = '',
                member_id = '',
                membership_id = '',
                subscribed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testMembershipSubscriptionDTO(self):
        """Test MembershipSubscriptionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
