# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_space_transaction_dto import CreateSpaceTransactionDTO

class TestCreateSpaceTransactionDTO(unittest.TestCase):
    """CreateSpaceTransactionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSpaceTransactionDTO:
        """Test CreateSpaceTransactionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSpaceTransactionDTO`
        """
        model = CreateSpaceTransactionDTO()
        if include_optional:
            return CreateSpaceTransactionDTO(
                type = 'deposit',
                amount = '',
                comment = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = 'magic',
                target = 'magic'
            )
        else:
            return CreateSpaceTransactionDTO(
                type = 'deposit',
                amount = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCreateSpaceTransactionDTO(self):
        """Test CreateSpaceTransactionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
