# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.acs_keys_api import AcsKeysApi


class TestAcsKeysApi(unittest.TestCase):
    """AcsKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AcsKeysApi()

    def tearDown(self) -> None:
        pass

    def test_a_cs_keys_controller_create(self) -> None:
        """Test case for a_cs_keys_controller_create

        Create ACS key
        """
        pass

    def test_a_cs_keys_controller_find_all_by_member_id(self) -> None:
        """Test case for a_cs_keys_controller_find_all_by_member_id

        Get ACS keys for specific member
        """
        pass

    def test_a_cs_keys_controller_remove(self) -> None:
        """Test case for a_cs_keys_controller_remove

        Delete ACS key
        """
        pass


if __name__ == '__main__':
    unittest.main()
