# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_macdto import CreateMACDTO

class TestCreateMACDTO(unittest.TestCase):
    """CreateMACDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMACDTO:
        """Test CreateMACDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMACDTO`
        """
        model = CreateMACDTO()
        if include_optional:
            return CreateMACDTO(
                member_id = '',
                mac = '',
                description = ''
            )
        else:
            return CreateMACDTO(
                member_id = '',
                mac = '',
                description = '',
        )
        """

    def testCreateMACDTO(self):
        """Test CreateMACDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
