# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.member_transactions_api import MemberTransactionsApi


class TestMemberTransactionsApi(unittest.TestCase):
    """MemberTransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemberTransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_member_transactions_controller_create(self) -> None:
        """Test case for member_transactions_controller_create

        Create new member transaction
        """
        pass

    def test_member_transactions_controller_find_all(self) -> None:
        """Test case for member_transactions_controller_find_all

        Get all member transactions
        """
        pass

    def test_member_transactions_controller_find_all_by_actor_member(self) -> None:
        """Test case for member_transactions_controller_find_all_by_actor_member

        Get all member transactions for actor member
        """
        pass

    def test_member_transactions_controller_find_all_by_subject_member(self) -> None:
        """Test case for member_transactions_controller_find_all_by_subject_member

        Get all member transactions for subject member
        """
        pass


if __name__ == '__main__':
    unittest.main()
