# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.member_stats_dto import MemberStatsDTO

class TestMemberStatsDTO(unittest.TestCase):
    """MemberStatsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemberStatsDTO:
        """Test MemberStatsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemberStatsDTO`
        """
        model = MemberStatsDTO()
        if include_optional:
            return MemberStatsDTO(
                count = 1.337
            )
        else:
            return MemberStatsDTO(
                count = 1.337,
        )
        """

    def testMemberStatsDTO(self):
        """Test MemberStatsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
