# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.space_api import SpaceApi


class TestSpaceApi(unittest.TestCase):
    """SpaceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpaceApi()

    def tearDown(self) -> None:
        pass

    def test_space_controller_get_balance(self) -> None:
        """Test case for space_controller_get_balance

        Get space balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
