# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.space_transactions_api import SpaceTransactionsApi


class TestSpaceTransactionsApi(unittest.TestCase):
    """SpaceTransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpaceTransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_space_transactions_controller_create(self) -> None:
        """Test case for space_transactions_controller_create

        Create new space transaction
        """
        pass

    def test_space_transactions_controller_find_all(self) -> None:
        """Test case for space_transactions_controller_find_all

        Get all space transactions
        """
        pass

    def test_space_transactions_controller_find_all_by_actor(self) -> None:
        """Test case for space_transactions_controller_find_all_by_actor

        Get all space transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
