# coding: utf-8

"""
    RE: Swynca

    B4CKSP4CE member/money management system

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.members_api import MembersApi


class TestMembersApi(unittest.TestCase):
    """MembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembersApi()

    def tearDown(self) -> None:
        pass

    def test_members_controller_create(self) -> None:
        """Test case for members_controller_create

        Create new member
        """
        pass

    def test_members_controller_delete_git_hub_metadata(self) -> None:
        """Test case for members_controller_delete_git_hub_metadata

        Delete GitHub metadata for member
        """
        pass

    def test_members_controller_delete_telegram_metadata(self) -> None:
        """Test case for members_controller_delete_telegram_metadata

        Delete Telegram metadata for member
        """
        pass

    def test_members_controller_find_all(self) -> None:
        """Test case for members_controller_find_all

        Get info about all members
        """
        pass

    def test_members_controller_find_by_id(self) -> None:
        """Test case for members_controller_find_by_id

        Get full info about member
        """
        pass

    def test_members_controller_stats(self) -> None:
        """Test case for members_controller_stats

        Get stats of all members
        """
        pass

    def test_members_controller_update(self) -> None:
        """Test case for members_controller_update

        Update member
        """
        pass

    def test_members_controller_update_git_hub_metadata(self) -> None:
        """Test case for members_controller_update_git_hub_metadata

        Add/update GitHub metadata for member
        """
        pass

    def test_members_controller_update_status(self) -> None:
        """Test case for members_controller_update_status

        Freeze/unfreeze member
        """
        pass

    def test_members_controller_update_telegram_metadata(self) -> None:
        """Test case for members_controller_update_telegram_metadata

        Add/update Telegram metadata for member
        """
        pass


if __name__ == '__main__':
    unittest.main()
