# coding: utf-8

# flake8: noqa
"""
    swynca mvp api for tg bot

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.error import Error
from openapi_client.models.resident import Resident
from openapi_client.models.transaction import Transaction
